version: '3.9'

volumes:
  r_libs:
    name: r_libs
    external: true
  rstudio:
    name: rstudio
    external: true
  mysqldb:
    name: mysqldb
    external: true

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      - TZ=Asia/Seoul    
      - MYSQL_ROOT_PASSWORD=1111
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysqldb
        target: /var/lib/mysql
      - type: bind
        source: ../workspace
        target: /workspace
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  
  python:
    container_name: python-data
    build:
      context: .
      dockerfile: dockerfile-py
    image: python-data:siu
    restart: always
    environment:
      - TZ=Asia/Seoul
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ../workspace
        target: /workspace

  rstudio:
    container_name: rstudio
    build:
      context: .
      dockerfile: dockerfile-R
    image: rocker/rstudio-kr:siu
    environment:
      - PASSWORD=1111
      - TZ=Asia/Seoul
    ports:
      - "8787:8787"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ../workspace
        target: /home/rstudio/projects
      - type: volume
        source: rstudio
        target: /home/rstudio
      - type: volume
        source: r_libs
        target: /usr/local/lib/R


