version: '3.9'

volumes:
  r_libs:
    name: r_libs
  rstudio:
    name: rstudio
  mysqldb:
    name: mysqldb

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul    
      - MYSQL_ROOT_PASSWORD=1111
    volumes:
      - type: volume
        source: mysqldb
        target: /var/lib/mysql
      - type: bind
        source: ../sql
        target: /workspace
  
  python:
    container_name: python-data
    build:
      context: .
      dockerfile: dockerfile-py
    image: python-data:siu
    environment:
      - TZ=Asia/Seoul
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - type: bind
        source: ../python
        target: /workspace
        read_only: false

  rstudio:
    container_name: rstudio
    build:
      context: .
      dockerfile: dockerfile-R
    image: rocker/rstudio-kr:siu
    environment:
      - PASSWORD=1111
      - TZ=Asia/Seoul
    ports:
      - "8787:8787"
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ../R/projects
        target: /home/rstudio/projects
      - type: volume
        source: rstudio
        target: /home/rstudio
      - type: volume
        source: r_libs
        target: /usr/local/lib/R


